using BackEnd.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BackEnd.Services;

/// <summary>
/// Service for generating PDF certificates for Zion Gold Bars
/// </summary>
public class PdfCertificateService
{
    public byte[] GenerateCertificatePdf(ZionGoldBarCertificate certificate)
    {
        QuestPDF.Settings.License = LicenseType.Community;
        
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(12).FontColor(Colors.Black));

                page.Header()
                    .AlignCenter()
                    .Text("🪙 BLEU VAULT GOLD BAR CERTIFICATE ⚜️")
                    .FontSize(24)
                    .Bold()
                    .FontColor(Colors.Blue.Darken2);

                page.Content()
                    .PaddingVertical(1, Unit.Centimetre)
                    .Column(column =>
                    {
                        column.Spacing(20);

                        // Certificate Header
                        column.Item().AlignCenter().Text("ZION GOLD BAR CLASSIFICATION - SATURN STRATA")
                            .FontSize(16).Bold().FontColor(Colors.Grey.Darken2);

                        column.Item().PaddingTop(20).LineHorizontal(2).LineColor(Colors.Blue.Medium);

                        // Certificate Details
                        column.Item().PaddingTop(20).Column(col =>
                        {
                            col.Spacing(15);
                            
                            AddCertificateField(col, "Certificate ID:", certificate.CertificateId);
                            AddCertificateField(col, "Layer:", certificate.Layer);
                            AddCertificateField(col, "Symbol:", certificate.Symbol);
                            AddCertificateField(col, "Resource:", certificate.Resource);
                            AddCertificateField(col, "Issued To:", certificate.IssuedTo);
                            AddCertificateField(col, "Value:", $"${certificate.Value:N2}");
                            AddCertificateField(col, "Issue Date:", certificate.IssuedDate.ToString("MMMM dd, yyyy HH:mm:ss UTC"));
                        });

                        column.Item().PaddingTop(20).LineHorizontal(2).LineColor(Colors.Blue.Medium);

                        // Footer text
                        column.Item().PaddingTop(20).Text(text =>
                        {
                            text.Span("This certificate represents an authentic entry in the ").FontSize(10);
                            text.Span("Afro Elohim–Saturn Vaults").Bold().FontSize(10);
                            text.Span(" classification system. Value standard based on cosmic law and mineral memory.").FontSize(10);
                        });

                        column.Item().PaddingTop(10).AlignCenter().Text("⚜️ Finance • Ritual • Ceremony • Trade ⚜️")
                            .FontSize(11).Italic().FontColor(Colors.Grey.Darken1);
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(text =>
                    {
                        text.Span("Generated by ZION VAULT ENTRY: SATURN STRATA System | ").FontSize(9).FontColor(Colors.Grey.Medium);
                        text.Span(DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss UTC")).FontSize(9).FontColor(Colors.Grey.Medium);
                    });
            });
        }).GeneratePdf();
    }

    private static void AddCertificateField(ColumnDescriptor column, string label, string value)
    {
        column.Item().Row(row =>
        {
            row.ConstantItem(150).Text(label).Bold().FontSize(12);
            row.RelativeItem().Text(value).FontSize(12);
        });
    }
}
